"""SQLAlchemy ORM models for Semantic Memory and Memory Curator (Phase 18).

Supports multi-tenant long-term semantic memory persistence, tags,
importance weighting, soft-deletion grace periods, cluster summarization,
and autonomous curator run reports.
"""

from __future__ import annotations

import json
import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import Boolean, DateTime, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base


class SemanticMemory(Base):
    """User long-term semantic memory entity."""

    __tablename__ = "semantic_memories"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    user_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    importance: Mapped[str] = mapped_column(
        String(20), nullable=False, default="normal"
    )  # low, normal, high, forever
    source: Mapped[str] = mapped_column(
        String(50), nullable=False, default="user:explicit"
    )  # user:explicit, agent:chat, agent:study, agent:coding, job:curator, system:extracted
    tags: Mapped[str | None] = mapped_column(String(255), nullable=True)  # Comma-separated
    is_soft_deleted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    soft_deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    soft_delete_reason: Mapped[str | None] = mapped_column(String(255), nullable=True)
    cluster_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    source_entry_ids: Mapped[str | None] = mapped_column(Text, nullable=True)  # Comma-separated IDs if summarized
    retrieval_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_retrieved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        nullable=False,
    )

    __table_args__ = (
        Index("ix_semantic_memories_user_active", "user_id", "is_soft_deleted"),
        Index("ix_semantic_memories_user_imp", "user_id", "importance"),
        Index("ix_semantic_memories_user_created", "user_id", "created_at"),
    )

    def to_dict(self) -> dict[str, Any]:
        tag_list: list[str] = []
        if self.tags:
            tag_list = [t.strip() for t in self.tags.split(",") if t.strip()]

        source_ids: list[str] = []
        if self.source_entry_ids:
            source_ids = [s.strip() for s in self.source_entry_ids.split(",") if s.strip()]

        return {
            "id": self.id,
            "user_id": self.user_id,
            "content": self.content,
            "importance": self.importance,
            "source": self.source,
            "tags": tag_list,
            "is_soft_deleted": self.is_soft_deleted,
            "soft_deleted_at": self.soft_deleted_at.isoformat() if self.soft_deleted_at else None,
            "soft_delete_reason": self.soft_delete_reason,
            "cluster_id": self.cluster_id,
            "source_entry_ids": source_ids,
            "retrieval_count": self.retrieval_count,
            "last_retrieved_at": self.last_retrieved_at.isoformat() if self.last_retrieved_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class CuratorRunReport(Base):
    """Execution audit report generated by the Memory Curator pass."""

    __tablename__ = "curator_run_reports"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    user_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    entries_scanned: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    summarized_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    clusters_formed: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON formatted cluster info
    soft_deleted_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    hard_deleted_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    errors_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    duration_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="completed")  # completed, failed
    diff_summary: Mapped[str] = mapped_column(Text, nullable=False, default="")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )

    __table_args__ = (
        Index("ix_curator_reports_user_created", "user_id", "created_at"),
    )

    def to_dict(self) -> dict[str, Any]:
        clusters: list[Any] = []
        if self.clusters_formed:
            try:
                clusters = json.loads(self.clusters_formed)
            except Exception:
                clusters = [self.clusters_formed]

        return {
            "id": self.id,
            "user_id": self.user_id,
            "entries_scanned": self.entries_scanned,
            "summarized_count": self.summarized_count,
            "clusters_formed": clusters,
            "soft_deleted_count": self.soft_deleted_count,
            "hard_deleted_count": self.hard_deleted_count,
            "errors_count": self.errors_count,
            "duration_ms": self.duration_ms,
            "status": self.status,
            "diff_summary": self.diff_summary,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
